## miniconf makefiles ## 1.1 ##

TOPDIR := ../..

configure_src = configure.c
configure_cflags = -DPLUGIN $(GTK2_CFLAGS) 
configure_libs = $(GTK2_LIBS) 
configure_type = lib 

include $(TOPDIR)/.config/rules.mk
