## miniconf makefiles ## 1.1 ##

TOPDIR := ..

SUBDIRS := battery \
    battery2 \
    chart \
    cpu \
    dclock \
    deskno \
    deskno2 \
    genmon \
    icons \
    image \
    launchbar \
    mem \
    mem2 \
    menu \
    meter \
    net \
    pager \
    separator \
    space \
    systray \
    taskbar \
    tclock \
    volume \
    volume2 \
    wincmd

include $(TOPDIR)/.config/rules.mk
