## miniconf makefiles ## 1.1 ##

TOPDIR := ../..

backlight_src = backlight.c
backlight_cflags = -DPLUGIN $(GTK2_CFLAGS)
backlight_libs = $(GTK2_LIBS)
backlight_type = lib

include $(TOPDIR)/.config/rules.mk
