## miniconf makefiles ## 1.1 ##

TOPDIR := ../..

volume2_src = volume2.c
volume2_cflags = -DPLUGIN $(GTK2_CFLAGS) $(ALSA_CFLAGS)
volume2_libs = $(GTK2_LIBS) $(ALSA_LIBS)
volume2_type = lib

include $(TOPDIR)/.config/rules.mk
