## miniconf makefiles ## 1.1 ##

TOPDIR := ../..

battery2_src = battery.c 
battery2_cflags = -DPLUGIN $(GTK2_CFLAGS) 
battery2_libs = $(GTK2_LIBS) 
battery2_type = lib 

include $(TOPDIR)/.config/rules.mk
